name: My CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Server Image
        run: docker build -t myapp-server:latest ./server

      - name: Build Client Image
        run: docker build -t myapp-client:latest ./client

      # Optional: If you want to run tests or further steps, add them here.
      
      # Optionally, push images to a registry:
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push Server Image
      #   run: |
      #     docker tag myapp-server:latest yourusername/myapp-server:latest
      #     docker push yourusername/myapp-server:latest
      #
      # - name: Push Client Image
      #   run: |
      #     docker tag myapp-client:latest yourusername/myapp-client:latest
      #     docker push yourusername/myapp-client:latest
